["protostar.config"]
protostar_version = "0.5.0"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]

erc20 = [
    "src/min_erc20/ERC20.cairo",
]

ens = [
    "src/min_ens/ens.cairo",
]

amm = [
    "src/min_amm/amm.cairo",
]

erc721 = [
    "src/min_erc721/ERC721.cairo",
]
