["protostar.config"]
protostar_version = "0.5.0"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]

erc20 = [
    "src/min-erc20/ERC20.cairo",
]

ens = [
    "src/min-ens/ens.cairo",
]
