[project]
protostar-version = "0.8.1"
lib-path = "lib"
cairo-path = ["lib"]

[contracts]
erc20 = ["src/min_erc20/ERC20.cairo"]
ens = ["src/min_ens/ens.cairo"]
amm = ["src/min_amm/amm.cairo"]
erc721 = ["src/min_erc721/ERC721.cairo"]
ico = ["src/min_ico/ico.cairo"]
nft_market = ["src/min_nft_marketplace/nft_market.cairo"]
staking = ["src/min_staking/staking.cairo"]
bridge_erc20 = ["src/min_messaging_bridge/L2/token/ERC20.cairo"]
bridge = ["src/min_messaging_bridge/L2/token_bridge.cairo"]